# Generated by Django 5.2.17 on 2026-10-07 14:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

from core.db import enable_rls


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("boutiques", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("encaissement", "Encaissement"),
                            ("depense", "Dépense"),
                            ("ouverture", "Solde d'ouverture"),
                            ("ajustement", "Correction de solde"),
                            ("transfert_sortie", "Transfert (sortie)"),
                            ("transfert_entree", "Transfert (entrée)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "compte",
                    models.CharField(
                        choices=[
                            ("caisse", "Caisse"),
                            ("wave", "Wave"),
                            ("orange_money", "Orange Money"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "montant",
                    models.BigIntegerField(
                        help_text="FCFA, signé : effet sur le solde."
                    ),
                ),
                (
                    "date_operation",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("categorie", models.CharField(blank=True, max_length=60)),
                ("note", models.CharField(blank=True, max_length=500)),
                (
                    "transfert_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "annulation_de",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="annulee_par",
                        to="tresorerie.transaction",
                    ),
                ),
                (
                    "boutique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="boutiques.boutique",
                    ),
                ),
            ],
            options={
                "db_table": "transaction_financiere",
                "ordering": ["-date_operation", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["boutique", "-date_operation"], name="tx_boutique_date"
                    ),
                    models.Index(
                        fields=["boutique", "compte"], name="tx_boutique_compte"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("annulation_de__isnull", True),
                                ("montant__gte", 0),
                                (
                                    "type__in",
                                    ("encaissement", "ouverture", "transfert_entree"),
                                ),
                            ),
                            models.Q(
                                ("annulation_de__isnull", False),
                                ("montant__lte", 0),
                                (
                                    "type__in",
                                    ("encaissement", "ouverture", "transfert_entree"),
                                ),
                            ),
                            models.Q(
                                ("annulation_de__isnull", True),
                                ("montant__lt", 0),
                                ("type__in", ("depense", "transfert_sortie")),
                            ),
                            models.Q(
                                ("annulation_de__isnull", False),
                                ("montant__gt", 0),
                                ("type__in", ("depense", "transfert_sortie")),
                            ),
                            models.Q(
                                ("type", "ajustement"),
                                models.Q(("montant", 0), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="tx_signe_selon_type",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("montant__gt", -1000000000000),
                            ("montant__lt", 1000000000000),
                        ),
                        name="tx_montant_borne",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("annulation_de__isnull", True), ("type", "ouverture")
                        ),
                        fields=("boutique", "compte"),
                        name="tx_une_ouverture_par_compte",
                    ),
                ],
            },
        ),
        enable_rls("transaction_financiere"),
    ]
