# Generated by Django 5.2.17 on 2026-10-07 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tresorerie", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="annulation_de",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="annulee_par",
                to="tresorerie.transaction",
            ),
        ),
    ]
