# Generated by Django 5.2.17 on 2026-10-01 09:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models

from core.db import enable_rls


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Boutique",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("nom", models.CharField(max_length=120)),
                ("activite", models.CharField(blank=True, max_length=80)),
            ],
            options={
                "db_table": "boutique",
            },
        ),
        migrations.CreateModel(
            name="Membre",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.UUIDField(db_index=True)),
                (
                    "role",
                    models.CharField(
                        choices=[("proprietaire", "Propriétaire")],
                        default="proprietaire",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "boutique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membres",
                        to="boutiques.boutique",
                    ),
                ),
            ],
            options={
                "db_table": "boutique_membre",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("boutique", "user_id"),
                        name="membre_unique_par_boutique",
                    )
                ],
            },
        ),
        enable_rls("boutique", "boutique_membre"),
    ]
